<?php

namespace Database\Seeders;

use App\Models\Atividade;
use Illuminate\Database\Seeder;

class AtividadeSeeder extends Seeder
{
    public function run(): void
    {
        $atividades = [
            ['nome' => 'Alongamento - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O alongamento traz muitos benefícios físicos, em especial no que diz respeito à prevenção de problemas na coluna, auxiliando na correção da postura.'],
            ['nome' => 'Basquetebol - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O curso de Basquetebol do CEPEUSP é oferecido para aqueles que desejam iniciar na modalidade e destina-se ao público USP e externo.'],
            ['nome' => 'Remo - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O curso tem três níveis e o pré-requisito é saber nadar. Além das habilidades próprias da modalidade, o aluno adquire e aprimora a forma física, preparando-se para competições.'],
            ['nome' => 'Atividade Física para Gestantes - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O curso compõe-se de exercícios de fortalecimento de grupos musculares responsáveis pela estabilidade da postura da gestante. É indicado para gestantes a partir do terceiro mês de gravidez.'],
            ['nome' => 'Atividade Física para Coluna Adaptado - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O programa consiste em exercícios de alongamento, relaxamento, flexibilidade, mobilidade articular e fortalecimento muscular.'],
            ['nome' => 'Capoeira - USP e externo', 'tipo' => 'semestral', 'descricao' => 'A Capoeira mistura elementos de jogo, luta e dança. Desenvolve ritmo, coordenação motora, força, resistência e flexibilidade, promovendo saúde e qualidade de vida.'],
            ['nome' => 'Tenis - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O curso tem dois níveis. No primeiro, o aluno aprende os movimentos básicos como batidas de esquerda e direita, voleio e outros. No segundo nível aprimoram-se as habilidades já adquiridas.'],
            ['nome' => 'Natação - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O curso tem três níveis. Nível iniciante: movimentos básicos e o estilo crawl. Nível dois: aprimoram-se os estilos crawl, peito, costas e borboleta. Nível três: os alunos praticam todos os estilos.'],
            ['nome' => 'Treinamento Funcional - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Condicionamento físico global, com foco na melhoria da amplitude e mobilidade articular, além de trabalhar a força e a resistência muscular.'],
            ['nome' => 'Ginástica - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Os exercícios cardiovasculares e os de resistência muscular são próprios para esta faixa etária. A música e variações nas estratégias tornam as aulas motivantes.'],
            ['nome' => 'Circuito 60+ - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Trata-se de um programa de condicionamento físico composto de caminhada, exercícios para o fortalecimento muscular e alongamento. As aulas, ministradas ao ar livre, são um atrativo especial.'],
            ['nome' => 'Yoga Adulto e 60+ - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Este curso proporciona ao aluno a aprendizagem dos conceitos básicos do Hatha Yoga, trabalhando flexibilidade, equilíbrio e estabilidade, através da prática das diversas posturas.'],
            ['nome' => 'Musculação - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Após uma fase inicial de adaptação aos aparelhos, o aluno passa a treinar sob orientação personalizada, dando-se maior autonomia para quem já é praticante da modalidade.'],
            ['nome' => 'Condicionamento Físico Feminino - USP e externo', 'tipo' => 'semestral', 'descricao' => 'As aulas consistem em exercícios de resistência muscular localizada, alongamentos e relaxamento, além de orientação para exercícios aeróbicos.'],
            ['nome' => 'Deep Running - Trimestral - USP e externo', 'tipo' => 'trimestral', 'descricao' => 'Promove a melhoria do condicionamento cardiovascular sem causar impacto articular. Na posição vertical, o aluno executa a corrida sem que seus pés toquem no fundo da piscina.'],
            ['nome' => 'Educação Física - USP e externo', 'tipo' => 'semestral', 'descricao' => 'É um curso com exercícios variados em que as aulas são focadas na vivência de diferentes materiais e ministradas em diversos ambientes, tais como meio aquático, ar livre e sala de ginástica.'],
            ['nome' => 'Ginástica Feminina - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Direcionado para mulheres a partir de 30 anos, o curso consiste em atividades aeróbias, exercícios localizados, alongamentos e relaxamentos ministrados com música.'],
            ['nome' => 'Ginástica Masculina - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Programa de condicionamento físico geral para homens acima de 30 anos. Engloba resistência aeróbia e resistência muscular, além de jogos recreativos: basquetebol, futebol e voleibol.'],
            ['nome' => 'Hidroginástica Trimestral - USP e externo', 'tipo' => 'trimestral', 'descricao' => 'É uma atividade que visa à melhoria do condicionamento físico global, aproveitando, principalmente, as propriedades físicas do meio líquido, como flutuação e resistência.'],
            ['nome' => 'Karatê - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Além das habilidades próprias desta modalidade de defesa pessoal como socos, chutes e esquivas, o aluno aperfeiçoa seu equilíbrio físico e mental, contribuindo para a formação do seu caráter.'],
            ['nome' => 'Atividade Física Individualizada - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Curso composto de caminhada, bicicleta, ginástica localizada, exercícios resistidos, alongamento e relaxamento. Visa a melhoria da resistência cardiovascular, muscular e da flexibilidade.'],
            ['nome' => 'Atividade Física para Coluna/Joelho Adaptado - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Atividade indicada para pessoas com alterações posturais, lesões ortopédicas da coluna vertebral, pós-traumatismos (joelho, ombro), pós-AVE, osteoporose, fibromialgia entre outros.'],
            ['nome' => 'Caminhada e Alongamento - USP e externo', 'tipo' => 'semestral', 'descricao' => 'A preparação, com aquecimento e alongamento adequados, é importante para se fazer uma boa caminhada.'],
            ['nome' => 'Canoagem - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Neste curso o aluno aprende as técnicas de remada, desenvolvendo o equilíbrio e a flexibilidade, em águas calmas, corredeiras e mar. O pré-requisito é saber nadar 100m sem parar.'],
            ['nome' => 'Corrida de Rua - USP e externo', 'tipo' => 'semestral', 'descricao' => 'A prática regular da modalidade melhora o sistema cardiorrespiratório e vascular. O curso é composto por corrida, caminhada, exercícios localizados de força, além de flexibilidade e coordenação.'],
            ['nome' => 'Futebol Masculino - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O conteúdo abrange a aprendizagem dos fundamentos básicos, a aquisição de habilidades técnicas e valores de convivência social, cooperação e trabalho em equipe.'],
            ['nome' => 'Judô - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Os alunos aprendem as técnicas do Judô, seus princípios básicos e avançados e as regras oficiais, com ênfase em sua filosofia, além de serem preparados para competições internas e externas.'],
            ['nome' => 'Mat Pilates - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Aplicando-se os métodos próprios desta modalidade, o curso visa melhorar a postura, a resistência, a mobilidade articular, a flexibilidade, com exercícios realizados no solo e em aparelhos.'],
            ['nome' => 'Orientação Nutricional - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Neste curso, os alunos recebem orientação sobre os princípios básicos de uma dieta equilibrada, com vista à formação de novos hábitos alimentares.'],
            ['nome' => 'Voleibol - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O aluno aprende as regras básicas da modalidade e desenvolve as habilidades necessárias para o jogo, tais como técnicas de saque, recepções, cortadas, levando a situações de jogo. Nível iniciante.'],
            ['nome' => 'Ginástica Localizada - USP', 'tipo' => 'semestral', 'descricao' => 'Esta modalidade compõe-se de exercícios de força e resistência muscular localizada e exercícios, acompanhados por música, com a utilização de equipamentos ou da sobrecarga do peso corporal.'],
            ['nome' => 'Canoagem/Remo Juvenil - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O curso tem dois níveis. O aluno desenvolve as habilidades próprias da modalidade e aprimora a forma física, preparando-se para competições.'],
            ['nome' => 'Ginástica 60+ - USP e externo', 'tipo' => 'semestral', 'descricao' => 'As aulas consistem em exercícios de resistência muscular localizados, alongamentos e relaxamento, com a utilização de música para marcação de movimentos rítmicos e contínuos.'],
            ['nome' => 'Musculação 60+ - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Ao passar por uma fase inicial de adaptação aos aparelhos, o aluno passa a treinar sob orientação personalizada, dando-se maior autonomia para quem já é praticante da modalidade.'],
            ['nome' => 'Musculação Funcional - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Musculação para pessoas que necessitam de fortalecimento muscular com recomendações médicas específicas, utilizando-se a musculação tradicional com as metodologias do treinamento funcional.'],
            ['nome' => 'Usuário 60+ - Externo', 'tipo' => 'semestral', 'descricao' => 'Atividade praticada espontaneamente por frequentadores do Centro que estejam nessa faixa etária. Por não se tratar de um curso regular, há um professor disponível para eventual orientação.'],
            ['nome' => 'Tecnicas de Meditaçao Adulto e 60+ - USP e externo', 'tipo' => 'semestral', 'descricao' => 'No curso o aluno tem uma visão abrangente sobre as técnicas e prática do Yoga, preparando-se para possibilidade da experiência meditativa.'],
            ['nome' => 'Futebol para pessoa com DI - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O curso tem como objetivo, entre outros, dar oportunidade para adultos, com deficiência intelectual - DI, jogarem futsal, de forma a interagirem com outros alunos sem deficiência.'],
            ['nome' => 'Fitness Intervalado - USP', 'tipo' => 'semestral', 'descricao' => 'Modalidade que alterna exercícios aeróbios e localizados combinados com a prática do fitness convencional, contribuindo para reduzir gordura e aumentar a resistência aeróbia.'],
            ['nome' => 'Futebol Feminino - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O curso destina-se às iniciantes, bem como às que já praticam a modalidade. Haverá abordagens sobre conteúdos, habilidades motoras, capacidades físicas e sobre as táticas do jogo em si.'],
            ['nome' => 'Exercício Físico para Emagrecimento - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O curso combina atividade física aplicada a cada caso. É destinado ao público adulto, a partir de 18 anos.'],
            ['nome' => 'Orientação Nutricional para Emagrecimento - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O curso procura orientar os alunos de forma adequada a fim de viabilizar a aquisição de novos hábitos alimentares, com vistas à redução de peso.'],
            ['nome' => 'Stand Up - USP', 'tipo' => 'semestral', 'descricao' => 'Modalidade esportiva praticada com utilização de prancha, muito difundida atualmente. O Curso é destinado à comunidade USP, a partir de 18 anos. É necessário saber nadar.'],
            ['nome' => 'Condicionamento Físico - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O curso de Condicionamento Físico é voltado aos iniciantes e é composto por atividades físicas aeróbias, caminhadas, corridas e exercícios localizados de força, entre outros.'],
            ['nome' => 'Futsal - USP e Externo', 'tipo' => 'semestral', 'descricao' => 'O curso de Futsal Feminino r Masculino é destinado às comunidades USP e externa. O objetivo é ensinar os conceitos e as habilidades específicas da modalidade, além de abordagens pedagógicas.'],
            ['nome' => 'Modalidades Esportivas Alternativas - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O curso possibilita a prática de modalidades como Roundnet, Kinball, Tchoukball, Badminton, Silver Vôlei e outras, utilizando o modelo pedagógico desenvolvido pelo CEPEUSP, através do PRODHE.'],
            ['nome' => 'Caminhada Longa - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O curso ensina a técnica do Caminhar e algumas atividades complementares como força e flexibilidade. É uma atividade física de múltiplas alternativas.'],
            ['nome' => '60+ USP Pró-Reitoria - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Cursos destinados a pessoas na faixa etária a partir de 60 anos, nas modalidades capoeira 50+, circuito, técnicas de meditação e Yoga.'],
            ['nome' => 'Canoagem - Reabilitação pós Câncer de Mama - REMAMA - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O Programa consiste em contribuir para melhorar as condições de vida de mulheres que tiveram câncer de mama, através da prática da canoagem em barco Dragon Boat.'],
            ['nome' => 'Circuito Treinamento de Força - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O curso tem por base treinos em circuito, com exercícios de resistência de força, combinados com exercícios aeróbios, propiciando aumento de força muscular e a capacidade cardiorrespiratória.'],
            ['nome' => 'Capoeira Infantil - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O curso visa promover o aprendizado da Capoeira, seus movimentos, musicalidade, história e filosofia, de forma lúdica, com jogos e brincadeiras, respeitando o ritmo de aprendizagem dos alunos.'],
            ['nome' => 'Capoeira 50+ - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Para pessoas a partir de 50 anos. O curso traz a ginga e os movimentos básicos da modalidade de forma lúdica, trabalhando a parte rítmica e musical com instrumentos e cantorias.'],
            ['nome' => 'Capoeira Inclusiva para pessoa com DI - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Curso para pessoas com deficiência intelectual e síndrome de down - DI. Visa promover o desenvolvimento físico, emocional, intelectual, social e cultural, através da vivência da Capoeira.'],
            ['nome' => 'Corrida de Rua/Atletismo - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O curso visa aprimorar a condição física geral dos participantes, além dos benefícios psíquicos e sociais que podem ser obtidos com a prática desta modalidade. É ministrado nos níveis I e II.'],
            ['nome' => 'Karatê Feminino - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Com o objetivo de aumentar o público feminino na modalidade, o curso de Karatê do CEPEUSP, em parceria com a FPKT e JKA-SP, agora tem a opção de turma exclusiva para mulheres.'],
            ['nome' => 'Tenis de Mesa - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Curso especial, oferecido também para portadores de Parkinson. É destinado ao público USP e externo, na faixa etária a partir de 18 anos, nível I (iniciantes).'],
            ['nome' => 'Moestabilidade - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Treino com exercícios de mobilidade e estabilidade. Visa a melhoria da performance do praticante, seja em suas atividades diárias ou em alguma modalidade esportiva.'],
            ['nome' => 'Natação Trimestral - USP e externo', 'tipo' => 'trimestral', 'descricao' => 'O curso tem dois níveis. Nível iniciante: movimentos básicos e o estilo crawl. Nível dois: aprimoram-se os estilos crawl, peito, costas e borboleta.'],
            ['nome' => 'Atividades Físicas Integradas 60+ - USP e externo', 'tipo' => 'semestral', 'descricao' => 'São aulas destinadas ao público 60+, cujo programa de exercícios consistem em práticas corporais e esportivas adaptadas, visando propiciar ao praticante um envelhecimento ativo e saudável.'],
            ['nome' => 'Badminton - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O curso é para quem possui pouco ou nenhum conhecimento da modalidade. Além das regras básicas, há atividades práticas em duplas e em grupo, trabalhando táticas em situações de jogo.'],
            ['nome' => 'Musculação Profilática para o Esporte - USP', 'tipo' => 'semestral', 'descricao' => 'O curso consiste em um treinamento de força para a melhoria do desempenho do atleta ou do praticante de alguma modalidade esportiva, com exercícios que propiciam a prevenção de lesões.'],
            ['nome' => 'HIIT - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O HIIT, com uma aula dinâmica, utiliza estações com exercícios aeróbios, que possibilitam elevar a potência e a capacidade cardiorrespiratória, respeitando os limites e o ritmo dos participantes.'],
            ['nome' => 'Circuito Treinamento de Forca + HIIT – USP e externo', 'tipo' => 'semestral', 'descricao' => 'O curso é uma combinação das duas modalidades, reúne o treinamento resistido com o treino de alta intensidade. É para quem tem experiência com atividade física de intensidade moderada a alta.'],
            ['nome' => 'Treinamento de Canoagem e Velocidade Juvenil - USP e Externo', 'tipo' => 'semestral', 'descricao' => 'Neste curso, que tem uma parceria com o COTP, os alunos aprendem as técnicas de remada nas modalidades de remo e canoagem, com o objetivo de formar atletas de ponta. Saiba mais.'],
            ['nome' => 'Futebol Juvenil - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Futebol de Campo para jovens de 15 a 18 anos. O curso tem como objetivo formar jogadores para participar de competições regionais, além de favorecer o desenvolvimento pessoal dos participantes.'],
            ['nome' => 'Corrida de Longa Distância - USP e externo', 'tipo' => 'semestral', 'descricao' => 'O curso tem como objetivo preparar atletas amadores para correr longas distâncias, incluindo meia-maratona (21 km), maratona (42 km) e ultramaratona (+42km), com treinos adequados aos objetivos de cada atleta.'],
            ['nome' => 'Boxe Educativo - USP e externo', 'tipo' => 'semestral', 'descricao' => 'Esta modalidade está sendo oferecida no curso de férias de inverno e é destinada a adultos e adolescentes a partir de 14 anos, para ambos os sexos. Confira a descrição do curso e os benefícios da prática da modalidade.'],
        ];

        foreach ($atividades as $atividade) {
            Atividade::updateOrCreate(['nome' => $atividade['nome']], $atividade);
        }
    }
}
