<?php

namespace Database\Seeders;

use App\Models\Oferecimento;
use App\Models\TaxaTurma;
use App\Models\Turma;
use App\Models\VagaTurma;
use Illuminate\Database\Seeder;

class TurmaSeeder extends Seeder
{
    public function run(): void
    {
        // chave = id do oferecimento (ID do post no w3cepe); 'vagas' e 'taxas' seguem o formato dos formulários:
        // vagas[perfil] = quantidade ou vagas[perfil][tamanho] = quantidade; taxas[periodo_inscricao][perfil] = valor
        $turmas = [
            97 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '08:00', 'horario_fim' => '09:00', 'professor' => 'Womualy - T-1 Alongamento', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'I-II / MF', 'local' => 'Sala 20 / Estádio', 'vagas' => ['tax_in' => 13, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '17:00', 'horario_fim' => '18:00', 'professor' => 'Carolina  -  T-2 Alongamento', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I  MF', 'local' => 'On Line', 'vagas' => ['tax_in' => 23, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '09:00', 'horario_fim' => '10:00', 'professor' => 'Vinicius - T-3 Alongamento e Mobilidade', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I-II / MF', 'local' => 'Espaço Multiuso', 'vagas' => ['tax_in' => 13, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '13:00', 'horario_fim' => '14:00', 'professor' => 'Carolina - T-4 Alongamento', 'idade_minima' => 18, 'local' => 'Sala 20 / Estádio', 'vagas' => ['tax_in' => 23, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '17:30', 'horario_fim' => '18:30', 'professor' => 'Pedro T-5 Alongamento', 'idade_minima' => 18, 'nivel' => 'I  MF', 'local' => 'Sala 16 Individualizada', 'vagas' => ['tax_in' => 20, 'tax_papfe' => 2, 'tax_ex' => 7], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 256, 'tax_ter' => 107], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 256, 'tax_ter' => 107]]],
            ],
            103 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '12:00', 'horario_fim' => '13:00', 'professor' => 'Katia  -  T-1 Basquetebol', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I MF', 'local' => 'Módulo 3', 'vagas' => ['tax_in' => 8, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            106 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta', 'sexta'], 'horario_inicio' => '06:30', 'horario_fim' => '08:00', 'professor' => 'Farah  - T1  Remo', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'II /  MF', 'local' => 'Raia Olimpica', 'vagas' => ['tax_in' => 13, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 597, 'tax_ter' => 289], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 597, 'tax_ter' => 289]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '17:30', 'horario_fim' => '18:30', 'professor' => 'Marcos Ito  - T2  Remo', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'II    MF', 'local' => 'Raia Olimpica', 'vagas' => ['tax_in' => 8, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '06:30', 'horario_fim' => '08:00', 'professor' => 'Farah  - T3  Remo', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I    MF', 'local' => 'Raia Olimpica', 'vagas' => ['tax_in' => 13, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '17:30', 'horario_fim' => '18:30', 'professor' => 'Marcos Ito  - T4  Remo', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I  MF', 'local' => 'Raia Olímpica', 'vagas' => ['tax_in' => 8, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'terca', 'quarta', 'quinta', 'sexta'], 'horario_inicio' => '16:00', 'horario_fim' => '19:00', 'professor' => 'Marcos Ito  - T5  *Remo 2ª a 6ª 16h', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => '*III  MF', 'local' => 'Raia olímpica', 'observacoes' => 'Alunos com nome na lista, solicitar boleto da inscrição no e-mail curspece@usp.br, com foto da carteira USP/CEPEUSP.', 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 694, 'tax_ter' => 289], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 694, 'tax_ter' => 289]]],
            ],
            109 => [
                ['sexo' => ['f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '09:00', 'horario_fim' => '10:00', 'professor' => 'Luzimar  -  T-1 Ativ.Física Gestante', 'idade_minima' => 14, 'idade_maxima' => 99, 'nivel' => 'I  F', 'local' => 'Sala 6 / estádio', 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263]]],
            ],
            112 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '08:00', 'horario_fim' => '09:00', 'professor' => 'Luzimar - T-1 Ativ. Física Coluna', 'idade_minima' => 14, 'idade_maxima' => 99, 'nivel' => 'I   MF', 'local' => 'Sala  6 / Estádio', 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263, 'tax_ter' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263, 'tax_ter' => 111]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '10:00', 'horario_fim' => '11:00', 'professor' => 'Luzimar  -  T-2 Ativ. Física Coluna', 'idade_minima' => 14, 'idade_maxima' => 99, 'nivel' => 'I   MF', 'local' => 'Sala 6 / estádio', 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263, 'tax_ter' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263, 'tax_ter' => 111]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '11:00', 'horario_fim' => '12:00', 'professor' => 'Luzimar  - T-3 Ativ. Física Coluna', 'idade_minima' => 14, 'idade_maxima' => 99, 'nivel' => 'I   MF', 'local' => 'Sala 2 e 6 / estádio', 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263, 'tax_ter' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263, 'tax_ter' => 111]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '17:00', 'horario_fim' => '18:00', 'professor' => 'Luzimar  -  T-4 Ativ. Física Coluna', 'idade_minima' => 14, 'nivel' => 'I   MF', 'local' => 'Sala 2 e 6 / estádio', 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263, 'tax_ter' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263, 'tax_ter' => 111]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '18:00', 'horario_fim' => '19:00', 'professor' => 'Luzimar  -  T-5 Ativ. Física Coluna', 'idade_minima' => 14, 'idade_maxima' => 99, 'nivel' => 'I   MF', 'local' => 'Sala 2 e 6 / estádio', 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263, 'tax_ter' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263, 'tax_ter' => 111]]],
            ],
            118 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '11:00', 'horario_fim' => '12:00', 'professor' => 'Womualy - T-1 Capoeira', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'I-II-III/ MF', 'local' => 'Sala 20 /Estádio', 'vagas' => ['tax_in' => 28, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '17:15', 'horario_fim' => '19:00', 'professor' => 'Vinicius - T-2 Capoeira', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'II / MF', 'local' => 'Espaço Multiuso', 'vagas' => ['tax_in' => 28, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '17:15', 'horario_fim' => '18:30', 'professor' => 'Vinicius - T-3 Capoeira', 'idade_minima' => 18, 'nivel' => 'I  MF', 'local' => 'Espaço Multiuso', 'vagas' => ['tax_in' => 28, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            124 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '09:00', 'horario_fim' => '10:00', 'professor' => 'Rafael - T1 Tênis', 'idade_minima' => 16, 'nivel' => 'I MF', 'local' => 'Quadras de Tênis  1 a 5', 'vagas' => ['tax_in' => 23, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '07:00', 'horario_fim' => '08:00', 'professor' => 'Rafael -  T2 Tênis', 'idade_minima' => 16, 'nivel' => 'I  MF', 'local' => 'Quadras de Tênis  1 a 5', 'vagas' => ['tax_in' => 23, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '08:00', 'horario_fim' => '09:00', 'professor' => 'Rafael - T3 Tênis', 'idade_minima' => 16, 'nivel' => 'II  MF', 'local' => 'Quadras de Tênis  1 a 5', 'vagas' => ['tax_in' => 13, 'tax_papfe' => 2, 'tax_ex' => 15], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '10:00', 'horario_fim' => '11:00', 'professor' => 'Rafael - T4 *Tênis', 'idade_minima' => 16, 'nivel' => 'II-III  MF', 'local' => 'Quadras de Tênis  1 a 5', 'observacoes' => 'Retirar filipeta/vaga com o professor no dia e horário da aula de 03 a  31/08/2026.', 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '09:00', 'horario_fim' => '10:00', 'professor' => 'Rafael - T5 *Tênis', 'idade_minima' => 16, 'nivel' => 'III  MF', 'local' => 'Quadras de Tênis  1 a 5', 'observacoes' => 'Retirar filipeta/vaga com o professor no dia e horário da aula de 03 a  31/08/2026.', 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['vagas' => ['tax_ex' => 0]],
            ],
            127 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '07:45', 'horario_fim' => '08:45', 'professor' => 'Mª Lourdes  -  T1 Natação', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I / MF', 'local' => 'Conjunto Aquático', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '11:00', 'horario_fim' => '12:00', 'professor' => 'Mª Lourdes  -  T2 Natação', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I /  MF', 'local' => 'Conjunto Aquático', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '12:00', 'horario_fim' => '13:00', 'professor' => 'Mª Lourdes -  T3 Natação', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'II / MF', 'local' => 'Conjunto Aquático', 'vagas' => ['tax_in' => 13, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['quarta', 'sexta'], 'horario_inicio' => '08:00', 'horario_fim' => '09:00', 'professor' => 'Mª Lourdes  -  T4 Natação', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'II / MF', 'local' => 'Conjunto Aquático', 'vagas' => ['tax_in' => 13, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['quarta', 'sexta'], 'horario_inicio' => '11:00', 'horario_fim' => '12:00', 'professor' => 'Mª Lourdes  -  T5 Natação', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I  / MF', 'local' => 'Conjunto Aquático', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['quarta', 'sexta'], 'horario_inicio' => '09:30', 'horario_fim' => '11:00', 'professor' => 'Mª Lourdes  -  T6* Natação', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'III / MF', 'local' => 'Conjunto Aquático', 'observacoes' => 'Retirar autorização com a professora no dia e horário da aula ou nome na lista de 11 a 31.08.26.', 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            132 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '07:15', 'horario_fim' => '08:00', 'professor' => 'Vera  - T1 Treinamento Funcional 2ª/4ª 07h15', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I/II  MF', 'local' => 'Sala Fitness', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '12:00', 'horario_fim' => '13:00', 'professor' => 'Vera  - T2 Treinamento Funcional 2ª/4ª 12h', 'idade_minima' => 18, 'nivel' => 'II-III / MF', 'local' => 'Sala 02 / Estádio e Pista', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            135 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '14:30', 'horario_fim' => '15:30', 'professor' => 'Patrícia Sakai  - T1 Ginástica', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I e II  MF', 'local' => 'Sala Individualizada', 'vagas' => ['tax_in' => 10, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '14:00', 'horario_fim' => '15:00', 'professor' => 'Carolina  -  T2 Ginástica', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I / MF', 'local' => 'Sala 20 / Estádio', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            141 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '08:00', 'horario_fim' => '09:00', 'professor' => 'Ana Cristina  -  T1 Circuito 60+', 'idade_minima' => 60, 'idade_maxima' => 99, 'nivel' => 'I / MF', 'local' => 'Pista / Sala 1 / Estádio', 'vagas' => ['tax_in' => 5, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '09:00', 'horario_fim' => '10:00', 'professor' => 'Ana Cristina  -  T2 Circuito 60+', 'idade_minima' => 60, 'idade_maxima' => 99, 'nivel' => 'I / MF', 'local' => 'Pista / Sala 1 / Estádio', 'vagas' => ['tax_in' => 5, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 214]]],
            ],
            423 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '08:00', 'horario_fim' => '09:00', 'professor' => 'Danilo  - T1 Yoga 2ª/4ª 08h', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I  MF', 'local' => 'Espaço Multiuso', 'vagas' => ['tax_in' => 38, 'tax_papfe' => 2, 'tax_ex' => 25], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '11:30', 'horario_fim' => '12:30', 'professor' => 'Danilo  - T2 Yoga 2ª/4ª 11h30', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I  MF', 'local' => 'Espaço Multiuso', 'vagas' => ['tax_in' => 38, 'tax_papfe' => 2, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '12:30', 'horario_fim' => '13:30', 'professor' => 'Danilo  - T3 Yoga 2ª/4ª 12h30', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I  MF', 'local' => 'Espaço Multiuso', 'vagas' => ['tax_in' => 38, 'tax_papfe' => 2, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '07:00', 'horario_fim' => '08:00', 'professor' => 'Danilo  - T4 Yoga 3ª/5ª 07h', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I  MF', 'local' => 'Espaço Multiuso', 'vagas' => ['tax_in' => 38, 'tax_papfe' => 2, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '14:30', 'horario_fim' => '15:30', 'professor' => 'Danilo  - T5 Yoga 3ª/5ª 14h30', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I  MF', 'local' => 'Espaço Multiuso', 'vagas' => ['tax_in' => 38, 'tax_papfe' => 2, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            924 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta', 'sexta'], 'horario_inicio' => '06:30', 'horario_fim' => '07:30', 'professor' => 'Guilherme - T1 - Musculação', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'I-II / MF', 'local' => 'Sala 22/ Estádio', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 597, 'tax_ter' => 289], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 597, 'tax_ter' => 289]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta', 'sexta'], 'horario_inicio' => '09:00', 'horario_fim' => '10:00', 'professor' => 'Womualy - T2 - Musculação', 'idade_minima' => 16, 'idade_maxima' => 59, 'nivel' => 'I /  MF', 'local' => 'Sala 22 / Estádio', 'vagas' => ['tax_in' => 15, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 597, 'tax_ter' => 289], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 597, 'tax_ter' => 289]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta', 'sexta'], 'horario_inicio' => '12:00', 'horario_fim' => '13:00', 'professor' => 'Guilherme - T3 - Musculação', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'II / MF', 'local' => 'Sala 22 / Estádio', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 597, 'tax_ter' => 289], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 597, 'tax_ter' => 289]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '17:00', 'horario_fim' => '18:00', 'professor' => 'Celso - T4 - Musculação', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I /  MF', 'local' => 'Sala 22 / Estádio', 'observacoes' => 'Apenas USP', 'vagas' => ['tax_in' => 23, 'tax_papfe' => 2, 'tax_ex' => 0], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '18:00', 'horario_fim' => '19:00', 'professor' => 'Celso - T5 - Musculação', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I / MF', 'local' => 'Sala 22 / Estádio', 'observacoes' => 'Apenas USP', 'vagas' => ['tax_in' => 23, 'tax_papfe' => 2], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '06:30', 'horario_fim' => '07:30', 'professor' => 'Guilherme - T6 - Musculação', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'I / MF', 'local' => 'Sala 22 / Estádio', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '09:00', 'horario_fim' => '10:00', 'professor' => 'Womualy - T7 Musculação', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'I / MF', 'local' => 'Sala 22 / Estádio', 'vagas' => ['tax_in' => 15, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '10:00', 'horario_fim' => '11:00', 'professor' => 'Guilherme - T8 - Musculação', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'I-II / MF', 'local' => 'Sala 22 / Estádio', 'vagas' => ['tax_in' => 13, 'tax_papfe' => 2, 'tax_ex' => 15], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '11:00', 'horario_fim' => '12:00', 'professor' => 'Paulo T9 Musculação', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I-II / MF', 'local' => 'Sala 22 / Estádio', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '12:00', 'horario_fim' => '13:00', 'professor' => 'Guilherme - T10 - Musculação', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'I-II / MF', 'local' => 'Sala 22 / Estádio', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '13:00', 'horario_fim' => '14:00', 'professor' => 'Paula - T11 - Musculação', 'idade_minima' => 18, 'idade_maxima' => 70, 'nivel' => 'I / MF', 'local' => 'Sala 22 / Estádio', 'observacoes' => 'Apenas USP', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 0], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '14:00', 'horario_fim' => '15:00', 'professor' => 'Paula - T12 - Musculação', 'idade_minima' => 18, 'idade_maxima' => 70, 'nivel' => 'II / MF', 'local' => 'Sala 22 / Estádio', 'observacoes' => 'Apenas USP', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '19:30', 'horario_fim' => '20:30', 'professor' => 'Signorini - T13 - Musculação', 'idade_minima' => 18, 'nivel' => 'II/MF', 'local' => 'Sala 22/Estádio', 'vagas' => ['tax_in' => 15, 'tax_papfe' => 2, 'tax_ex' => 3], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['quarta', 'sexta'], 'horario_inicio' => '16:00', 'horario_fim' => '17:00', 'professor' => 'Signorini - T14 - Musculação', 'idade_minima' => 18, 'nivel' => 'II  MF', 'local' => 'Sala 22 / Estádio', 'vagas' => ['tax_in' => 15, 'tax_papfe' => 2, 'tax_ex' => 3], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['quarta', 'sexta'], 'horario_inicio' => '19:00', 'horario_fim' => '20:30', 'professor' => 'Signorini - T15 - Musculação', 'idade_minima' => 18, 'nivel' => 'I  MF', 'local' => 'Sala 22 / Estádio', 'vagas' => ['tax_in' => 15, 'tax_papfe' => 2, 'tax_ex' => 3], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '16:00', 'horario_fim' => '19:00', 'professor' => 'Celso - T16* - Musculação', 'idade_minima' => 18, 'nivel' => 'II  MF', 'local' => 'Sala 22 Estádio', 'observacoes' => 'Retirar Autorização com o Professor', 'vagas' => ['tax_in' => 50, 'tax_papfe' => 0, 'tax_ex' => 0], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111]]],
            ],
            926 => [
                ['sexo' => ['f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '08:00', 'horario_fim' => '09:00', 'professor' => 'Fabiane  -  T1 Cond Fisico Feminino', 'idade_minima' => 30, 'idade_maxima' => 99, 'nivel' => 'II - F', 'local' => 'Sala Fitness', 'vagas' => ['tax_in' => 28, 'tax_papfe' => 2, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            928 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '12:00', 'horario_fim' => '13:00', 'professor' => 'Vera - T1 Deep Running', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I - II - III /MF', 'local' => 'Piscina Fundo Verde', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '14:00', 'horario_fim' => '15:00', 'professor' => 'Vera - T2 Deep Running', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I - II - III /MF', 'local' => 'Piscina Fundo Verde', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['quarta', 'sexta'], 'horario_inicio' => '09:00', 'horario_fim' => '10:00', 'professor' => 'Vera - T3 Deep Running', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I-II-III / MF', 'local' => 'Piscina Fundo verde', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161]]],
            ],
            929 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '09:00', 'horario_fim' => '10:30', 'professor' => 'Maria de  Lourdes  -  T1 Educação Física', 'idade_minima' => 35, 'idade_maxima' => 99, 'nivel' => 'I / MF', 'local' => 'Sala 16 Individualizada  e Piscina', 'observacoes' => 'Inicio das aulas 03 de agosto de 2026.', 'vagas' => ['tax_in' => 13, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            931 => [
                ['sexo' => ['f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '09:00', 'horario_fim' => '10:00', 'professor' => 'Patricia Sakai - T1 Ginástica Feminina', 'idade_minima' => 30, 'idade_maxima' => 99, 'nivel' => 'II  F', 'local' => 'Sala Individualizada', 'vagas' => ['tax_in' => 13, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            933 => [
                ['sexo' => ['m'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '19:00', 'horario_fim' => '21:00', 'professor' => 'Celso  -  T1 Ginastica masculina', 'idade_minima' => 30, 'idade_maxima' => 99, 'nivel' => 'I  M', 'local' => 'Sala Fitness e Módulo 6', 'vagas' => ['tax_in' => 15, 'tax_ex' => 15], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            934 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '09:00', 'horario_fim' => '10:00', 'professor' => 'Vera - T1 Hidroginástica', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I-II-III  MF', 'local' => 'Conjunto Aquático', 'observacoes' => 'Providenciar Atestado dermatológico.', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '10:00', 'horario_fim' => '11:00', 'professor' => 'Vera - T2 Hidroginástica', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I-II-III  MF', 'local' => 'Conjunto Aquático', 'observacoes' => 'Providenciar Atestado dermatológico.', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['quarta', 'sexta'], 'horario_inicio' => '10:00', 'horario_fim' => '11:00', 'professor' => 'Vera - T3 Hidroginástica', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I-II-III  MF', 'local' => 'Conjunto Aquático', 'observacoes' => 'Providenciar Atestado dermatológico.', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161]]],
            ],
            936 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '12:00', 'horario_fim' => '13:00', 'professor' => 'Fabiane - T1 Karate', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I - II / MF', 'local' => 'Módulo 5', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '17:00', 'horario_fim' => '18:00', 'professor' => 'Fabiane - T2 Karate', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I - II / MF', 'local' => 'Módulo 5', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            941 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta', 'sexta'], 'horario_inicio' => '07:00', 'horario_fim' => '09:00', 'professor' => 'Patricia Sakai  - T-1 Ativ. Fisica Individualizada', 'idade_minima' => 30, 'idade_maxima' => 99, 'nivel' => 'I - II  / MF', 'local' => 'Sala Individualizada', 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 597, 'tax_ter' => 289], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 597, 'tax_ter' => 289]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '07:00', 'horario_fim' => '09:00', 'professor' => 'Patricia Sakai - T-2 Ativ. Fisica Individualizada', 'idade_minima' => 30, 'idade_maxima' => 99, 'nivel' => 'I - II  / MF', 'local' => 'Sala Individualizada', 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            946 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '19:00', 'horario_fim' => '20:00', 'professor' => 'Luzimar  T-1 Ativ. Física Coluna Joelho', 'idade_minima' => 14, 'idade_maxima' => 99, 'nivel' => 'I  MF', 'local' => 'Salas 2 e 6 / estádio', 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263, 'tax_ter' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263, 'tax_ter' => 111]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '20:00', 'horario_fim' => '21:00', 'professor' => 'Luzimar  T-2 Ativ. Física Coluna Joelho', 'idade_minima' => 14, 'idade_maxima' => 99, 'nivel' => 'I  MF', 'local' => 'Salas 2 e 6 / estádio', 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263, 'tax_ter' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263, 'tax_ter' => 111]]],
            ],
            948 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '19:00', 'horario_fim' => '20:00', 'professor' => 'Carolina  -  T1 Caminhada e Alongamento', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I / MF', 'local' => 'Sala 20 / Estádio', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '19:00', 'horario_fim' => '20:00', 'professor' => 'Celso  -  T2 Caminhada e Alongamento', 'idade_minima' => 18, 'nivel' => 'I / MF', 'local' => 'Sala 2 / Estádio', 'vagas' => ['tax_in' => 13, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            950 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '08:00', 'horario_fim' => '09:00', 'professor' => 'Christian - T-1 Canoagem', 'idade_minima' => 17, 'idade_maxima' => 99, 'nivel' => 'I  MF', 'local' => 'Raia Olimpica', 'vagas' => ['tax_in' => 10, 'tax_papfe' => 2, 'tax_ex' => 3], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta', 'sexta'], 'horario_inicio' => '07:00', 'horario_fim' => '08:00', 'professor' => 'Christian - T-2 Canoagem', 'idade_minima' => 17, 'idade_maxima' => 99, 'nivel' => 'I  MF', 'local' => 'Raia Olimpica', 'vagas' => ['tax_in' => 10, 'tax_papfe' => 2, 'tax_ex' => 3], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 597, 'tax_ter' => 289], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 597, 'tax_ter' => 289]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '07:00', 'horario_fim' => '08:00', 'professor' => 'Christian - T-3 Canoagem', 'idade_minima' => 17, 'idade_maxima' => 99, 'nivel' => 'I MF', 'local' => 'Raia Olímpica', 'vagas' => ['tax_in' => 10, 'tax_papfe' => 2, 'tax_ex' => 3], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '08:00', 'horario_fim' => '09:00', 'professor' => 'Christian - T-4 Canoagem', 'idade_minima' => 17, 'idade_maxima' => 99, 'nivel' => 'I MF', 'local' => 'Raia Olímpica', 'vagas' => ['tax_in' => 10, 'tax_papfe' => 2, 'tax_ex' => 3], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 694, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 694, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'terca', 'quarta', 'quinta', 'sexta'], 'horario_inicio' => '06:00', 'horario_fim' => '07:00', 'professor' => 'Christian - T-5* Canoagem', 'idade_minima' => 17, 'idade_maxima' => 99, 'nivel' => 'III MF', 'local' => 'Raia Olímpica', 'observacoes' => 'USP e Externo- Deve constar nome na lista do Professor.', 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 289], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 289]]],
            ],
            952 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '18:15', 'horario_fim' => '19:30', 'professor' => 'Paula -  T1 Corrida de Rua', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I-II / MF', 'local' => 'Pista e Sala 1 / Estádio', 'vagas' => ['tax_in' => 28, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '07:00', 'horario_fim' => '08:15', 'professor' => 'Paula -  T2 Corrida de Rua', 'idade_minima' => 18, 'nivel' => 'I-II / MF', 'local' => 'Pista e Sala 1 / Estádio', 'vagas' => ['tax_in' => 23, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '18:00', 'horario_fim' => '19:30', 'professor' => 'Paulo - T3 Corrida de Rua', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I-II/MF', 'local' => 'Pista e Sala 1 / Estádio', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            1226 => [
                ['sexo' => ['m'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '12:30', 'horario_fim' => '13:45', 'professor' => 'Maykell - T1 Futebol', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'II-III / M', 'local' => 'Campo 5', 'vagas' => ['tax_in' => 38, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '17:30', 'horario_fim' => '19:00', 'professor' => 'Maykell - T2 Futebol', 'idade_minima' => 30, 'idade_maxima' => 39, 'nivel' => 'II-III M', 'local' => 'Campo 5', 'vagas' => ['tax_in' => 8, 'tax_papfe' => 2, 'tax_ex' => 0], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_cepe' => 513], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_cepe' => 513]]],
                ['sexo' => ['m'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '17:30', 'horario_fim' => '19:00', 'professor' => 'Maykell - T3 Futebol', 'idade_minima' => 40, 'idade_maxima' => 99, 'nivel' => 'II-III M', 'local' => 'Campo 5', 'vagas' => ['tax_in' => 48, 'tax_papfe' => 0], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_cepe' => 513], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_cepe' => 513]]],
            ],
            1304 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '09:00', 'horario_fim' => '10:00', 'professor' => 'Fabiane - T1  Mat Pilates Alongamento 60+', 'idade_minima' => 60, 'idade_maxima' => 99, 'nivel' => 'I MF', 'local' => 'Sala Fitness', 'observacoes' => 'Apenas 60+ USP e Externo', 'vagas' => ['tax_in' => 25, 'tax_papfe' => 0, 'tax_ex' => 25], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '08:00', 'horario_fim' => '09:00', 'professor' => 'Fabiane - T2 Mat Pilates', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I-II  MF', 'local' => 'Sala Fitness', 'vagas' => ['tax_in' => 43, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '17:00', 'horario_fim' => '18:00', 'professor' => 'Erica - T3 Mat Pilates', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'I-II   MF', 'local' => 'Sala Fitness', 'vagas' => ['tax_in' => 40, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '11:00', 'horario_fim' => '12:00', 'professor' => 'Erica  - T4 Mat Pilates', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'I-II  MF', 'local' => 'Sala Fitness', 'vagas' => ['tax_in' => 35, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '12:00', 'horario_fim' => '13:00', 'professor' => 'Erica - T5 Mat Pilates', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'I-II  MF', 'local' => 'Sala Fitness', 'vagas' => ['tax_in' => 40, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '18:30', 'horario_fim' => '19:30', 'professor' => 'Erica - T6 Mat Pilates', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'I-II   MF', 'local' => 'Sala Fitness', 'vagas' => ['tax_in' => 40, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            1305 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca'], 'horario_inicio' => '09:30', 'horario_fim' => '10:30', 'professor' => 'Patricia Peres - T1 Orient Nutricional', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'I-II-III MF', 'local' => 'On-line', 'vagas' => ['tax_in' => 13, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 263, 'tax_ter' => 107], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 263, 'tax_ter' => 107]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['quarta'], 'horario_inicio' => '13:00', 'horario_fim' => '14:00', 'professor' => 'Patricia Peres - T2 Orient Nutricional', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'I-II-III MF', 'local' => 'On-line', 'vagas' => ['tax_in' => 13, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 263, 'tax_ter' => 107], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 263, 'tax_ter' => 107]]],
            ],
            1308 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '15:30', 'horario_fim' => '17:00', 'professor' => 'Paulo - T1 Voleibol 50+  2ª/4ª  15h30', 'idade_minima' => 50, 'idade_maxima' => 99, 'nivel' => 'II  MF', 'local' => 'Módulos 1 e 2', 'vagas' => ['tax_in' => 20, 'tax_papfe' => 0, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta', 'sexta'], 'horario_inicio' => '06:45', 'horario_fim' => '08:00', 'professor' => 'Ana Cristina - T2 Voleibol 2ª/4ª/6ª 06h45', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I MF', 'local' => 'Módulos 1 e 2', 'observacoes' => 'Apenas USP', 'vagas' => ['tax_in' => 28, 'tax_papfe' => 2], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '11:00', 'horario_fim' => '12:15', 'professor' => 'Ana Cristina - T3 Voleibol 3ª/5ª 11h', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I  MF', 'local' => 'Módulos 1 e 2', 'observacoes' => 'Apenas USP', 'vagas' => ['tax_in' => 28, 'tax_papfe' => 2, 'tax_ex' => 0], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '12:15', 'horario_fim' => '13:30', 'professor' => 'Ana Cristina - T4 Voleibol 3ª/5ª 12h15', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I/MF', 'local' => 'Módulos 1 e 2', 'observacoes' => 'Apenas USP', 'vagas' => ['tax_in' => 28, 'tax_papfe' => 2, 'tax_ex' => 0], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111]]],
            ],
            2149 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '12:00', 'horario_fim' => '13:00', 'professor' => 'Fabiane  -  T1 Ginástica Localizada', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I - II - III /MF', 'local' => 'Sala 1 / Estádio', 'observacoes' => 'Apenas USP', 'vagas' => ['tax_in' => 33, 'tax_papfe' => 2, 'tax_ex' => 0], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 214]]],
            ],
            2172 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '15:00', 'horario_fim' => '16:00', 'professor' => 'Marcos Ito - T-1 Canoagem Remo Juvenil', 'idade_minima' => 13, 'idade_maxima' => 18, 'nivel' => 'I - II  / MF', 'local' => 'Raia Olimpica', 'vagas' => ['tax_in' => 10, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513]]],
            ],
            2275 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '09:00', 'horario_fim' => '10:00', 'professor' => 'Fabiane  -  T1 Ginástica 60+', 'idade_minima' => 60, 'idade_maxima' => 99, 'nivel' => 'II / MF', 'local' => 'Sala Fitness', 'vagas' => ['tax_in' => 25, 'tax_ex' => 25], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 214]]],
            ],
            2283 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta', 'sexta'], 'horario_inicio' => '07:30', 'horario_fim' => '08:30', 'professor' => 'Guilherme - T1 Musculaçao 60+', 'idade_minima' => 60, 'idade_maxima' => 99, 'nivel' => 'I-II  MF', 'local' => 'Sala 22 / Estádio', 'vagas' => ['tax_in' => 10, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 289], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 289]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '07:30', 'horario_fim' => '08:30', 'professor' => 'Guilherme - T1 Musculaçao 60+', 'idade_minima' => 60, 'idade_maxima' => 99, 'nivel' => 'I-II MF', 'local' => 'Sala 22 / Estádio', 'vagas' => ['tax_in' => 10, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 214]]],
                ['horario_inicio' => '00:30', 'horario_fim' => '00:00', 'idade_minima' => 60, 'idade_maxima' => 99, 'vagas' => ['tax_in' => 10, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 107], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 107]]],
                ['horario_inicio' => '09:30', 'horario_fim' => '10:30', 'idade_maxima' => 99, 'taxas' => [1 => ['tax_ter' => 107], 2 => ['tax_ter' => 107]]],
                ['horario_inicio' => '09:30', 'horario_fim' => '00:30', 'idade_minima' => 60, 'idade_maxima' => 99, 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 145], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 145]]],
            ],
            2679 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta', 'sexta'], 'horario_inicio' => '11:00', 'horario_fim' => '12:00', 'professor' => 'Vinicius  -  T1 Musculação Funcional', 'idade_minima' => 35, 'nivel' => 'I-II  MF', 'local' => 'Sala 22 / Estádio', 'vagas' => ['tax_in' => 15, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 597, 'tax_ter' => 289], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 597, 'tax_ter' => 289]]],
            ],
            2861 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'terca', 'quarta', 'quinta', 'sexta'], 'horario_inicio' => '07:00', 'horario_fim' => '17:00', 'professor' => 'Erica - alunos que ja estão inscrito em alguma atividade.', 'idade_minima' => 60, 'idade_maxima' => 99, 'nivel' => 'I e II /MF', 'local' => 'Praça de Esportes', 'observacoes' => 'Uso livre das dependências da instituição, com exceção do Complexo Aquático e da Raia Olímpica.', 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 51, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 51, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'terca', 'quarta', 'quinta', 'sexta'], 'horario_inicio' => '07:00', 'horario_fim' => '17:00', 'professor' => 'Erica - T2 Alunos que utilizam livre sem matricula em curso.', 'idade_minima' => 60, 'idade_maxima' => 99, 'nivel' => 'I-II / MF', 'local' => 'Praça de Esportes', 'observacoes' => 'Uso livre das dependências da instituição, com exceção do Complexo Aquático e da Raia Olímpica.', 'taxas' => [1 => ['tax_ter' => 428], 2 => ['tax_ter' => 428]]],
            ],
            2902 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '09:00', 'horario_fim' => '10:00', 'professor' => 'Danilo  - T1 Técnicas de Meditação', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I  MF', 'local' => 'Espaço Multiuso', 'vagas' => ['tax_in' => 28, 'tax_papfe' => 2, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            2921 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['quarta', 'sexta'], 'horario_inicio' => '15:00', 'horario_fim' => '16:15', 'professor' => 'Carolina - T1 Futebol adaptado para Pessoas DI', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'I /MF', 'local' => 'Quadra Externa 4 e módulos 3 e 4', 'observacoes' => 'De 03 a 31 de agosto retirar autorização com o professor(a).', 'taxas' => [1 => ['tax_in' => 73, 'tax_child' => 73, 'tax_ex' => 73], 2 => ['tax_in' => 73, 'tax_child' => 73, 'tax_ex' => 73]]],
            ],
            4686 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '18:00', 'horario_fim' => '19:00', 'professor' => 'Erica - T1 Fitness Intervalado', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'I - II  /MF', 'local' => 'Sala Fitness', 'observacoes' => 'Apenas USP', 'vagas' => ['tax_in' => 40, 'tax_papfe' => 2, 'tax_ex' => 0], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111]]],
            ],
            4732 => [
                ['sexo' => ['f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '12:00', 'horario_fim' => '13:00', 'professor' => 'Rafael -  T1  Futebol Feminino', 'idade_minima' => 15, 'idade_maxima' => 99, 'nivel' => 'I-II / F', 'local' => 'Campo 5', 'vagas' => ['tax_in' => 15, 'tax_papfe' => 2, 'tax_ex' => 15], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            5623 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '18:00', 'horario_fim' => '19:00', 'professor' => 'Carolina - T1 Exerc. Fisico p/Emagrecimento', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I / MF', 'local' => 'Sala 20 / Estádio', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '12:00', 'horario_fim' => '13:00', 'professor' => 'Carolina - T2 Exerc. Fisico p/Emagrecimento', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I / MF', 'local' => 'Sala 20 / Estádio', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            5673 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda'], 'horario_inicio' => '12:00', 'horario_fim' => '13:00', 'professor' => 'Patricia Peres - T1 Orient Nutric Emagrecimento', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'I - II - III / MF', 'local' => 'Sala Individualizada', 'vagas' => ['tax_in' => 8, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 263, 'tax_ter' => 107], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 263, 'tax_ter' => 107]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['quinta'], 'horario_inicio' => '17:00', 'horario_fim' => '18:00', 'professor' => 'Patricia Peres - T2 Orient Nutric Emagrecimento', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'I - II - III / MF', 'local' => 'On-line', 'vagas' => ['tax_in' => 8, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 263, 'tax_ter' => 107], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 263, 'tax_ter' => 107]]],
            ],
            5737 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['sexta'], 'horario_inicio' => '08:00', 'horario_fim' => '09:00', 'professor' => 'Marcos Ito -  T1 Stand Up 08h', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I - II / MF', 'local' => 'Raia Olímpica', 'observacoes' => 'apenas USP', 'vagas' => ['tax_in' => 5, 'tax_papfe' => 0, 'tax_ex' => 0], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111]]],
            ],
            5856 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '17:30', 'horario_fim' => '18:30', 'professor' => 'Paulo - T1 Condicionamento Físico', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'Todos /MF', 'local' => 'Sala 16 Individualizada', 'vagas' => ['tax_in' => 20, 'tax_papfe' => 2, 'tax_ex' => 8], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '17:30', 'horario_fim' => '18:30', 'professor' => 'Erica - T2 Condicionamento Físico', 'idade_minima' => 16, 'nivel' => 'I-II / MF', 'local' => 'Sala Fitness', 'vagas' => ['tax_in' => 40, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '16:30', 'horario_fim' => '17:30', 'professor' => 'Pedro - T-3 Condicionamento Físico', 'idade_minima' => 18, 'nivel' => 'I  MF', 'local' => 'Sala 16 Individualizada', 'observacoes' => 'inicio a partir de 21.09.2026', 'vagas' => ['tax_in' => 20, 'tax_papfe' => 2, 'tax_ex' => 7], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 256, 'tax_ter' => 107], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 256, 'tax_ter' => 107]]],
            ],
            6237 => [
                ['sexo' => ['f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '12:15', 'horario_fim' => '13:15', 'professor' => 'Paulo  -  T1 FUTSAL Feminino', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I-II  F', 'local' => 'Módulo 4', 'vagas' => ['tax_in' => 13, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m'], 'dias_semana' => ['quarta', 'sexta'], 'horario_inicio' => '12:00', 'horario_fim' => '13:00', 'professor' => 'Rafael - T2 FUTSAL Masculino', 'idade_minima' => 17, 'nivel' => 'I-II / M', 'local' => 'Módulos 3 e 4', 'vagas' => ['tax_in' => 15, 'tax_papfe' => 2, 'tax_ex' => 8], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            6418 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '16:30', 'horario_fim' => '17:30', 'professor' => 'Marcos Vinicius e Maykell  - T1 Modalidades Esportivas Alternativa', 'idade_minima' => 14, 'idade_maxima' => 99, 'nivel' => 'I - II - III / MF', 'local' => 'Módulos 4 e 6', 'vagas' => ['tax_in' => 23, 'tax_papfe' => 2, 'tax_ex' => 15], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            6426 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '07:00', 'horario_fim' => '08:00', 'professor' => 'Bezerra -  T-1 Caminhada Longa', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I-II /  MF', 'local' => 'Barra de Alongamento / Trilha', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            6597 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['quarta', 'sexta'], 'horario_inicio' => '10:00', 'horario_fim' => '11:00', 'professor' => 'Vinicius T-1  Capoeira 50+ 4ª/6ª 10h', 'idade_minima' => 60, 'idade_maxima' => 99, 'nivel' => 'I-II  MF', 'local' => 'Espaço Multiuso', 'vagas' => ['tax_in' => 0, 'tax_papfe' => 0, 'tax_ex' => 10], 'taxas' => [1 => ['tax_ex' => 5, 'tax_ter' => 5, 'tax_cepe' => 5], 2 => ['tax_ex' => 5, 'tax_ter' => 5]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '08:00', 'horario_fim' => '09:00', 'professor' => 'Ana Cristina T-2  Circuito 60+ 2ª/4ª 08h', 'idade_minima' => 60, 'idade_maxima' => 99, 'nivel' => 'II  MF', 'local' => 'Pista e Sala Fitness', 'vagas' => ['tax_in' => 0, 'tax_papfe' => 0, 'tax_ex' => 2], 'taxas' => [1 => ['tax_ex' => 5, 'tax_ter' => 5], 2 => ['tax_ex' => 5, 'tax_ter' => 5]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '09:00', 'horario_fim' => '10:00', 'professor' => 'Ana Cristina T-3  Circuito 60+ 2ª/4ª 09h', 'idade_minima' => 60, 'idade_maxima' => 99, 'nivel' => 'II / MF', 'local' => 'Pista e Sala Fitness', 'vagas' => ['tax_in' => 0, 'tax_papfe' => 0, 'tax_ex' => 2], 'taxas' => [1 => ['tax_ex' => 5, 'tax_ter' => 5], 2 => ['tax_ex' => 5, 'tax_ter' => 5]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '09:00', 'horario_fim' => '10:00', 'professor' => 'Danilo T-4  Técnicas de Meditação 2ª/4ª 09h', 'idade_minima' => 60, 'idade_maxima' => 99, 'nivel' => 'I  MF', 'local' => 'Espaço Multiuso', 'vagas' => ['tax_in' => 0, 'tax_papfe' => 0, 'tax_ex' => 2], 'taxas' => [1 => ['tax_ex' => 5, 'tax_ter' => 5], 2 => ['tax_ex' => 5, 'tax_ter' => 5]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '08:00', 'horario_fim' => '09:00', 'professor' => 'Danilo T-5  Yoga 2ª/4ª 08h', 'idade_minima' => 60, 'nivel' => 'I  MF', 'local' => 'Espaço Multiuso', 'vagas' => ['tax_in' => 0, 'tax_papfe' => 0, 'tax_ex' => 2], 'taxas' => [1 => ['tax_ex' => 5, 'tax_ter' => 5], 2 => ['tax_ex' => 5, 'tax_ter' => 5]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '11:30', 'horario_fim' => '12:30', 'professor' => 'Danilo T-6  Yoga 2ª/4ª 11h30', 'idade_minima' => 60, 'nivel' => 'I  MF', 'local' => 'Espaço Multiuso', 'vagas' => ['tax_in' => 0, 'tax_papfe' => 0, 'tax_ex' => 2], 'taxas' => [1 => ['tax_ex' => 5, 'tax_ter' => 5], 2 => ['tax_ex' => 5, 'tax_ter' => 5]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '12:30', 'horario_fim' => '13:30', 'professor' => 'Danilo T-7  Yoga 2ª/4ª 12h30', 'idade_minima' => 60, 'nivel' => 'I  MF', 'local' => 'Espaço Multiuso', 'vagas' => ['tax_in' => 0, 'tax_papfe' => 0, 'tax_ex' => 2], 'taxas' => [1 => ['tax_ex' => 5, 'tax_ter' => 5], 2 => ['tax_ex' => 5, 'tax_ter' => 5]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '07:00', 'horario_fim' => '08:00', 'professor' => 'Danilo T-8  Yoga 3ª/5ª 07h', 'idade_minima' => 60, 'nivel' => 'I  MF', 'local' => 'Espaço Multiuso', 'vagas' => ['tax_in' => 0, 'tax_papfe' => 0, 'tax_ex' => 2], 'taxas' => [1 => ['tax_ex' => 5, 'tax_ter' => 5], 2 => ['tax_ex' => 5, 'tax_ter' => 5]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '14:30', 'horario_fim' => '15:30', 'professor' => 'Danilo T-9  Yoga 3ª/5ª 14h30', 'idade_minima' => 60, 'nivel' => 'I  MF', 'local' => 'Espaço Multiuso', 'vagas' => ['tax_in' => 0, 'tax_papfe' => 0, 'tax_ex' => 2], 'taxas' => [1 => ['tax_ex' => 5, 'tax_ter' => 5], 2 => ['tax_ex' => 5, 'tax_ter' => 5]]],
                ['vagas' => ['tax_in' => 0]],
            ],
            6676 => [
                ['sexo' => ['f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '08:00', 'horario_fim' => '09:00', 'professor' => 'Christian - T1 Canoagem REMAMA*', 'idade_minima' => 17, 'idade_maxima' => 99, 'nivel' => 'I / F', 'local' => 'Raia Olímpica', 'observacoes' => 'Falar com o Professor no dia e horário da aula com Atestado e relatório.'],
                ['sexo' => ['f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '09:00', 'horario_fim' => '10:00', 'professor' => 'Christian - T-2 Canoagem REMAMA*', 'idade_minima' => 17, 'idade_maxima' => 99, 'nivel' => 'I / F', 'local' => 'Raia Olímpica', 'observacoes' => 'Falar com o Professor no dia e horário da aula com Atestado e relatório.'],
            ],
            8025 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '07:00', 'horario_fim' => '08:00', 'professor' => 'Womualy  -  T1 Circuito Treinamento de Forca', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'Todos /MF', 'local' => 'Sala 2 / Estádio', 'vagas' => ['tax_in' => 13, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '10:00', 'horario_fim' => '11:00', 'professor' => 'Womualy  -  T2 CircuitoTreinamento de Forca', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'I-II / MF', 'local' => 'Sala 2 / Estádio', 'vagas' => ['tax_in' => 13, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '12:00', 'horario_fim' => '13:00', 'professor' => 'Womualy  -  T3 Circuito', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'I-II / MF', 'local' => 'Sala 2 / Estádio', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            20854 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['quinta'], 'horario_inicio' => '10:00', 'horario_fim' => '11:00', 'professor' => 'Vinicius - T1 Capoeira Infantil', 'idade_minima' => 7, 'idade_maxima' => 11, 'nivel' => 'I-II  / MF', 'local' => 'Espaço Multiuso', 'vagas' => ['tax_in' => 10, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263], 2 => ['tax_in' => 50, 'tax_child' => 111, 'tax_ex' => 263]]],
            ],
            21606 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['quarta', 'sexta'], 'horario_inicio' => '10:00', 'horario_fim' => '11:00', 'professor' => 'Vinícius - T1 Capoeira 50+', 'idade_minima' => 50, 'idade_maxima' => 99, 'nivel' => 'I - II / MF', 'local' => 'Espaço Multiuso', 'vagas' => ['tax_in' => 15, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            21608 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['quarta'], 'horario_inicio' => '14:00', 'horario_fim' => '15:00', 'professor' => 'Vinicius - T1 Capoeira Inclusiva para DI  4ª 14h', 'idade_minima' => 15, 'idade_maxima' => 99, 'nivel' => 'I - II / MF', 'local' => 'Espaço Multiuso', 'observacoes' => 'De 03 a 31/08/2026 retirar autorização com o professor(a).', 'taxas' => [1 => ['tax_in' => 73, 'tax_child' => 73, 'tax_ex' => 73], 2 => ['tax_in' => 73, 'tax_child' => 73, 'tax_ex' => 73]]],
            ],
            21844 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '17:00', 'horario_fim' => '18:15', 'professor' => 'Paula  - T1 Corrida de Rua/Atletismo', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I-II  /  MF', 'local' => 'Pista e Sala 1 / Estádio', 'vagas' => ['tax_in' => 28, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '08:15', 'horario_fim' => '09:30', 'professor' => 'Paula  - T2 Corrida de Rua/Atletismo', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I / MF', 'local' => 'Pista e Sala 1 / Estádio', 'vagas' => ['tax_in' => 23, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            23223 => [
                ['sexo' => ['f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '12:00', 'horario_fim' => '13:00', 'professor' => 'Fabiane - T1 Karate', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I - II / F', 'local' => 'Módulo 5', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            24110 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '07:00', 'horario_fim' => '08:00', 'professor' => 'Bezerra - T1 Tênis de Mesa', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I / MF', 'local' => 'Sala de Tênis de Mesa / Estádio', 'observacoes' => 'Apenas USP', 'info_contato' => 'Apenas USP', 'vagas' => ['tax_in' => 10, 'tax_papfe' => 2, 'tax_ex' => 0], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quarta'], 'horario_inicio' => '08:15', 'horario_fim' => '09:30', 'professor' => 'Bezerra  -  T2 Tênis de Mesa p/Parkinson', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I / MF', 'local' => 'Sala de Tênis de Mesa / Estádio', 'observacoes' => 'USP e externo', 'vagas' => ['tax_in' => 5, 'tax_papfe' => 0, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263, 'tax_ter' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263, 'tax_ter' => 111]]],
            ],
            25758 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['sexta'], 'horario_inicio' => '07:15', 'horario_fim' => '08:00', 'professor' => 'Vera T1 Moestabilidade', 'idade_minima' => 18, 'nivel' => 'II e III MF', 'local' => 'Sala de Fitness', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 263, 'tax_ter' => 107], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 263, 'tax_ter' => 107]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['sexta'], 'horario_inicio' => '12:00', 'horario_fim' => '13:00', 'professor' => 'Vera T2 Moestabilidade', 'idade_minima' => 18, 'nivel' => 'II-III / MF', 'local' => 'Sala Fitness', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263, 'tax_ter' => 107], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 263, 'tax_ter' => 107]]],
            ],
            25993 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '14:30', 'horario_fim' => '15:30', 'professor' => 'Paulo T1 Natação', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I / MF', 'local' => 'Conjunto Aquático', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '15:30', 'horario_fim' => '16:30', 'professor' => 'Paulo T2 Natação', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'II / MF', 'local' => 'Conjunto aquático', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['quarta', 'sexta'], 'horario_inicio' => '11:30', 'horario_fim' => '12:30', 'professor' => 'Paulo T3 Natação', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'II / MF', 'local' => 'Conjunto Aquático', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['quarta', 'sexta'], 'horario_inicio' => '12:30', 'horario_fim' => '13:30', 'professor' => 'Paulo T4 Natação', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'I / MF', 'local' => 'Conjunto Aquático', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161]]],
            ],
            26891 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta', 'sexta'], 'horario_inicio' => '08:30', 'horario_fim' => '09:30', 'professor' => 'Guilherme  -  T-1 Ativ. Física Integrada', 'idade_minima' => 60, 'idade_maxima' => 99, 'nivel' => 'I-II  MF', 'local' => 'Sala 2 / Estádio', 'vagas' => ['tax_in' => 10, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 289], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ter' => 289]]],
            ],
            27659 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '11:00', 'horario_fim' => '12:00', 'professor' => 'Paula  T1 Badminton', 'idade_minima' => 18, 'nivel' => 'I  MF', 'local' => 'Módulo 6', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '12:00', 'horario_fim' => '13:00', 'professor' => 'Paula  T2 Badminton', 'idade_minima' => 18, 'nivel' => 'II-III  MF', 'local' => 'Módulo 6', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['quarta', 'sexta'], 'horario_inicio' => '16:00', 'horario_fim' => '17:00', 'professor' => 'Katia  T3 Badminton', 'idade_minima' => 12, 'nivel' => 'I  MF', 'local' => 'Módulo 6', 'vagas' => ['tax_in' => 4, 'tax_papfe' => 2, 'tax_ex' => 6], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            27671 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['sexta'], 'horario_inicio' => '13:00', 'horario_fim' => '14:00', 'professor' => 'Paula  T-1 Musculação Profilática', 'idade_minima' => 18, 'idade_maxima' => 70, 'nivel' => 'I-II MF', 'local' => 'Sala 22 / Estádio', 'observacoes' => 'Apenas USP', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83], 2 => ['tax_in' => 51, 'tax_child' => 83]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['sexta'], 'horario_inicio' => '14:00', 'horario_fim' => '15:00', 'professor' => 'Paula  T-2 Musculação Profilática 6ª 14h', 'idade_minima' => 18, 'idade_maxima' => 70, 'nivel' => 'I-II MF', 'local' => 'Sala 22 / Estádio', 'observacoes' => 'Apenas USP', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83], 2 => ['tax_in' => 51, 'tax_child' => 83]]],
            ],
            27972 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '07:00', 'horario_fim' => '08:00', 'professor' => 'Womualy T-1 HIIT', 'idade_minima' => 16, 'nivel' => 'I-II   MF', 'local' => 'Sala 02 / Estádio', 'vagas' => ['tax_in' => 13, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '10:00', 'horario_fim' => '11:00', 'professor' => 'Womualy T-2 HIIT', 'idade_minima' => 16, 'nivel' => 'I-II   MF', 'local' => 'Sala 2 / Estádio', 'vagas' => ['tax_in' => 13, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
            ],
            27979 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'terca', 'quarta', 'quinta'], 'horario_inicio' => '07:00', 'horario_fim' => '08:00', 'professor' => 'Womualy - T1 Circuito Treinamento de Força + Hiit', 'idade_minima' => 16, 'nivel' => 'I-II   MF', 'local' => 'Sala 02 / Estádio', 'observacoes' => 'Apenas USP', 'info_contato' => 'Apenas USP', 'vagas' => ['tax_in' => 10, 'tax_papfe' => 0, 'tax_ex' => 0], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'terca', 'quarta', 'quinta'], 'horario_inicio' => '10:00', 'horario_fim' => '11:00', 'professor' => 'Womualy - T2 Circuito Treinamento de Força + Hiit', 'idade_minima' => 16, 'nivel' => 'I-II   MF', 'local' => 'Sala 02 / Estádio', 'observacoes' => 'Apenas USP', 'vagas' => ['tax_in' => 10, 'tax_papfe' => 0, 'tax_ex' => 0], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111], 2 => ['tax_in' => 51, 'tax_child' => 111]]],
            ],
            28140 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'terca', 'quarta', 'quinta', 'sexta'], 'horario_inicio' => '10:30', 'horario_fim' => '12:30', 'professor' => 'Marcos Ito  T-1 *Treinamento Canoagem e Velocidade Juvenil', 'idade_minima' => 11, 'idade_maxima' => 18, 'nivel' => 'II   MF', 'local' => 'Raia Olímpica', 'taxas' => [1 => ['tax_in' => 5, 'tax_child' => 5, 'tax_ex' => 5], 2 => ['tax_in' => 5, 'tax_child' => 5, 'tax_ex' => 5]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta', 'sexta'], 'horario_inicio' => '15:00', 'horario_fim' => '17:00', 'professor' => 'Marcos Ito  T-2 *Treinamento Canoagem e Velocidade Juvenil', 'idade_minima' => 11, 'idade_maxima' => 18, 'nivel' => 'II   MF', 'local' => 'Raia Olímpica', 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 5, 'tax_ex' => 5], 2 => ['tax_in' => 51, 'tax_child' => 5, 'tax_ex' => 5]]],
            ],
            32622 => [
                ['sexo' => ['m'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '15:00', 'horario_fim' => '16:00', 'professor' => 'Rafael - T1 Futebol Juvenil', 'idade_minima' => 15, 'idade_maxima' => 18, 'nivel' => 'I-II / MF', 'local' => 'Campo  5', 'vagas' => ['tax_in' => 15, 'tax_papfe' => 0, 'tax_ex' => 15], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513]]],
            ],
            32624 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta', 'sexta'], 'horario_inicio' => '07:00', 'horario_fim' => '08:30', 'professor' => 'Rafael - T1 Corrida Longa Distancia', 'idade_minima' => 17, 'nivel' => 'I-II-III/ MF', 'local' => 'Pista e Sala 1 Estádio', 'vagas' => ['tax_in' => 23, 'tax_papfe' => 2, 'tax_ex' => 10], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214], 2 => ['tax_in' => 51, 'tax_child' => 111, 'tax_ex' => 513, 'tax_ter' => 214]]],
                ['dias_semana' => ['sexta'], 'idade_minima' => 1],
            ],
            33709 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '17:30', 'horario_fim' => '18:30', 'professor' => 'Pedro - Alongamento T-1', 'idade_minima' => 18, 'nivel' => 'I MF', 'local' => 'Sala 16 Individualizada', 'vagas' => ['tax_in' => 20, 'tax_papfe' => 2, 'tax_ex' => 7], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '13:00', 'horario_fim' => '14:00', 'professor' => 'Pedro - Boxe Educativo T-2', 'idade_minima' => 18, 'nivel' => 'I MF', 'local' => 'Sala 02 Estádio', 'vagas' => ['tax_in' => 15, 'tax_papfe' => 2, 'tax_ex' => 3], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161]]],
                ['sexo' => ['m'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '18:00', 'horario_fim' => '19:00', 'professor' => 'Pedro - Boxe Educativo T-3', 'idade_minima' => 18, 'nivel' => 'I  M', 'local' => 'Sala 02 Estádio', 'vagas' => ['tax_in' => 15, 'tax_papfe' => 2, 'tax_ex' => 3], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161]]],
                ['sexo' => ['f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '13:00', 'horario_fim' => '14:00', 'professor' => 'Pedro - Boxe Educativo T-4', 'idade_minima' => 18, 'nivel' => 'I / F', 'local' => 'Sala 02 Estádio', 'vagas' => ['tax_in' => 15, 'tax_papfe' => 2, 'tax_ex' => 3], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '16:30', 'horario_fim' => '17:30', 'professor' => 'Pedro - Cond. Físico T-5', 'idade_minima' => 18, 'nivel' => 'I  MF', 'local' => 'Sala 16 Individualizada', 'vagas' => ['tax_in' => 20, 'tax_papfe' => 2, 'tax_ex' => 7], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '15:00', 'horario_fim' => '16:00', 'professor' => 'Fabiane - Judô T-6', 'idade_minima' => 16, 'nivel' => 'I MF', 'local' => 'Módulo 5', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['segunda', 'quarta'], 'horario_inicio' => '16:00', 'horario_fim' => '17:00', 'professor' => 'Fabiane - Judô T-7', 'idade_minima' => 16, 'nivel' => 'Avançado  II-III  MF', 'local' => 'Módulo 5', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 5], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['quarta', 'sexta'], 'horario_inicio' => '11:00', 'horario_fim' => '12:00', 'professor' => 'Pedro - Musculação T-8', 'idade_minima' => 18, 'nivel' => 'I  MF', 'local' => 'Sala de Musculação', 'vagas' => ['tax_in' => 20, 'tax_papfe' => 2, 'tax_ex' => 7], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161], 2 => ['tax_in' => 51, 'tax_child' => 83, 'tax_ex' => 383, 'tax_ter' => 161]]],
            ],
            27958 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['quarta', 'quinta'], 'horario_inicio' => '08:00', 'horario_fim' => '12:00', 'professor' => 'Guilherme Gabas', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'Todos', 'local' => 'Módulos', 'vagas' => ['tax_in' => 150, 'tax_ex' => 150], 'taxas' => [1 => ['tax_in' => 70, 'tax_child' => 70, 'tax_ex' => 70, 'tax_ter' => 70]]],
            ],
            33052 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quinta'], 'horario_inicio' => '12:00', 'horario_fim' => '13:00', 'professor' => 'Vera - Condicionamento Físico Intenso Turma 1 - 3ª/5ª 12h  04 a 27/08', 'idade_minima' => 18, 'nivel' => 'II-III/MF', 'local' => 'Pista e Módulo 6', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 52, 'tax_ex' => 130, 'tax_ter' => 54], 2 => ['tax_in' => 51, 'tax_child' => 52, 'tax_ex' => 130, 'tax_ter' => 54]]],
                ['sexo' => ['m', 'f'], 'dias_semana' => ['terca', 'quarta', 'quinta', 'sexta'], 'horario_inicio' => '09:30', 'horario_fim' => '10:30', 'professor' => 'Vera - Condicionamento Físico Intenso Turma 2 - 3ª a 6ª 12h  04 a 28/08', 'idade_minima' => 18, 'nivel' => 'II-III/MF', 'local' => 'Pista e Módulo 2-6', 'vagas' => ['tax_in' => 18, 'tax_papfe' => 2, 'tax_ex' => 20], 'taxas' => [1 => ['tax_in' => 51, 'tax_child' => 52, 'tax_ex' => 130, 'tax_ter' => 54], 2 => ['tax_in' => 51, 'tax_child' => 52, 'tax_ex' => 130, 'tax_ter' => 54]]],
            ],
            33115 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['sabado', 'domingo'], 'horario_inicio' => '08:00', 'horario_fim' => '17:00', 'professor' => 'Womualy', 'idade_minima' => 18, 'idade_maxima' => 99, 'nivel' => 'Todos', 'local' => 'Espaço Multiuso', 'vagas' => ['tax_in' => 100, 'tax_ex' => 100], 'taxas' => [1 => ['tax_in' => 50, 'tax_ex' => 50], 2 => ['tax_in' => 50, 'tax_ex' => 50]]],
            ],
            33463 => [
                ['sexo' => ['m', 'f'], 'dias_semana' => ['sexta'], 'horario_inicio' => '07:00', 'horario_fim' => '12:00', 'professor' => 'Rafael', 'idade_minima' => 16, 'idade_maxima' => 99, 'nivel' => 'Misto', 'local' => 'Quadras de Tênis 1 ao 5', 'observacoes' => 'Liga CEPEUSP de Tênis ( Torneio por Equipes) - Ler Regulamento
Trazer um Pack de Bolas para os jogos nos dias dos jogos.', 'vagas' => ['tax_in' => 80, 'tax_ex' => 80], 'taxas' => [1 => ['tax_in' => 35, 'tax_child' => 35, 'tax_ex' => 35, 'tax_ter' => 35, 'tax_cepe' => 35], 2 => ['tax_in' => 35, 'tax_child' => 35, 'tax_ex' => 35, 'tax_ter' => 35, 'tax_cepe' => 35]]],
            ],
            33608 => [
                ['horario_inicio' => '16:00', 'horario_fim' => '18:00', 'idade_minima' => 14, 'idade_maxima' => 100, 'vagas' => ['tax_in' => ['p' => 368, 'm' => 509, 'g' => 277, 'gg' => 79], 'tax_papfe' => ['p' => 16, 'm' => 21, 'g' => 10, 'gg' => 3], 'tax_ex' => ['p' => 134, 'm' => 226, 'g' => 95, 'gg' => 45], 'reservada' => ['p' => 52, 'm' => 84, 'g' => 58, 'gg' => 23]], 'taxas' => [1 => ['tax_in' => 50, 'tax_ex' => 50, 'tax_cepe' => 50]]],
            ],
            33657 => [
                ['horario_inicio' => '08:30', 'horario_fim' => '10:00', 'idade_minima' => 18, 'vagas' => ['tax_in' => ['pp' => 20, 'p' => 75, 'm' => 190, 'g' => 80, 'gg' => 100, 'exg' => 85]], 'taxas' => [1 => ['tax_in' => 30, 'tax_alumni' => 30]]],
            ],
            33747 => [
                ['horario_inicio' => '08:30', 'observacoes' => 'Nascidos em 2021 | Distância: 30 m | Concentração: 08:15 | Largada: 08:30', 'ano_nascimento_minimo' => 2021, 'ano_nascimento_maximo' => 2021, 'vagas' => ['tax_in' => [6 => 10, 8 => 16], 'reservada' => [8 => 4]], 'taxas' => [1 => ['tax_in' => 30]]],
                ['horario_inicio' => '11:30', 'observacoes' => 'Nascidos em 2020 | Distância: 30 m | Concentração: 11:15 | Largada: 11:30', 'ano_nascimento_minimo' => 2020, 'ano_nascimento_maximo' => 2020, 'vagas' => ['tax_in' => [8 => 16, 10 => 15], 'reservada' => [8 => 4]], 'taxas' => [1 => ['tax_in' => 30]]],
                ['horario_inicio' => '12:00', 'observacoes' => 'Nascidos em 2019 | Distância: 50 m | Concentração: 11:45 | Largada: 12:00', 'ano_nascimento_minimo' => 2019, 'ano_nascimento_maximo' => 2019, 'vagas' => ['tax_in' => [8 => 5, 10 => 40], 'reservada' => [10 => 10]], 'taxas' => [1 => ['tax_in' => 30]]],
                ['horario_inicio' => '12:30', 'observacoes' => 'Nascidos em 2018 | Distância: 50 m | Concentração: 12:15 | Largada: 12:30', 'ano_nascimento_minimo' => 2018, 'ano_nascimento_maximo' => 2018, 'vagas' => ['tax_in' => [10 => 5, 12 => 40, 14 => 5], 'reservada' => [12 => 10]], 'taxas' => [1 => ['tax_in' => 30]]],
                ['horario_inicio' => '13:00', 'observacoes' => 'Nascidos em 2017 | Distância: 50 m | Concentração: 12:45 | Largada: 13:00', 'ano_nascimento_minimo' => 2017, 'ano_nascimento_maximo' => 2017, 'vagas' => ['tax_in' => [12 => 10, 14 => 32, 'pp' => 10], 'reservada' => [14 => 8]], 'taxas' => [1 => ['tax_in' => 30]]],
                ['horario_inicio' => '10:00', 'observacoes' => 'Nascidos em 2016 | Distância: 100 m | Concentração: 09:45 | Largada: 10:00', 'ano_nascimento_minimo' => 2016, 'ano_nascimento_maximo' => 2016, 'vagas' => ['tax_in' => [14 => 15, 'pp' => 28], 'reservada' => ['pp' => 7]], 'taxas' => [1 => ['tax_in' => 30]]],
                ['horario_inicio' => '09:30', 'observacoes' => 'Nascidos em 2015 | Distância: 100 m | Concentração: 09:15 | Largada: 09:30', 'ano_nascimento_minimo' => 2015, 'ano_nascimento_maximo' => 2015, 'vagas' => ['tax_in' => [14 => 10, 'pp' => 16, 'p' => 16], 'reservada' => ['pp' => 4, 'p' => 4]], 'taxas' => [1 => ['tax_in' => 30]]],
                ['horario_inicio' => '09:00', 'observacoes' => 'Nascidos em 2014 | Distância: 100 m | Concentração: 08:45 | Largada: 09:00', 'ano_nascimento_minimo' => 2014, 'ano_nascimento_maximo' => 2014, 'vagas' => ['tax_in' => ['p' => 24, 'm' => 10], 'reservada' => ['p' => 6]], 'taxas' => [1 => ['tax_in' => 30]]],
                ['horario_inicio' => '08:30', 'observacoes' => 'Nascidos em 2013 e 2012 | Distância: 150 m | Concentração: 08:15 | Largada: 08:30', 'ano_nascimento_minimo' => 2012, 'ano_nascimento_maximo' => 2013, 'vagas' => ['tax_in' => ['p' => 8, 'm' => 8], 'reservada' => ['p' => 2, 'm' => 2]], 'taxas' => [1 => ['tax_in' => 30]]],
            ],
        ];

        foreach ($turmas as $oferecimentoId => $lista) {

            $oferecimento = Oferecimento::find($oferecimentoId);
            if (!$oferecimento) {
                continue;
            }

            if (Turma::where('oferecimento_id', $oferecimentoId)->exists()) {
                continue;
            }

            foreach ($lista as $dados) {
                $vagas = $dados['vagas'] ?? [];
                $taxas = $dados['taxas'] ?? [];
                unset($dados['vagas'], $dados['taxas']);

                $turma = Turma::create(['oferecimento_id' => $oferecimentoId] + $dados);

                foreach ($vagas as $perfil => $valor) {
                    foreach (is_array($valor) ? $valor : ['' => $valor] as $tamanho => $quantidade) {
                        VagaTurma::create([
                            'turma_id' => $turma->id,
                            'perfil' => $perfil,
                            'tamanho' => (string) $tamanho,
                            'quantidade' => $quantidade,
                        ]);
                    }
                }

                foreach ($taxas as $periodo => $porPerfil) {
                    foreach ($porPerfil as $perfil => $valor) {
                        TaxaTurma::create([
                            'turma_id' => $turma->id,
                            'perfil' => $perfil,
                            'periodo_inscricao' => $periodo,
                            'valor' => $valor,
                        ]);
                    }
                }
            }
        }
    }
}
